In [45]:
import numpy as np
from numpy import linalg as LA

## Creating Arrays

### 1d Arrays (Vectors)

In [46]:
np.array([1,7,9,0]) # Creates a 1X4 array of specific values

array([1, 7, 9, 0])

In [47]:
np.arange(1,5); # 1d array with consecutive terms

In [48]:
np.arange(7,45,10) # From 7 upto, but not exceeding, 45 by 10s

array([ 7, 17, 27, 37])

In [49]:
np.linspace(7, 37, 11) # From 7 to 45 with 11 evenly spaced entries

array([ 7., 10., 13., 16., 19., 22., 25., 28., 31., 34., 37.])

Note that in the commands above a semi-colon after a command suppresses the output.  This is helpful when you are entering initial values/variables but don't need to see the ourtput.

### 2d Arrays (Matrices)

In [50]:
I = np.eye(3) # 3x3 identity matrix
A = np.array([
    [2,0,1],
    [0,1,2],
    [0,0,3]
]) # Manually entered array
B = np.zeros((2,3)); # 2x3 zero matrix
C = np.ones((2,3)); # 2x3 matrix of ones

Working with rows and columns

In [51]:
print(A[0]) # this is a row of A, row numbers start at 0

[2 0 1]


In [52]:
print(I[:,1]) # this is a column of I, numbering again starts at 0

[0. 1. 0.]


In [53]:
2*A[1]+1 # we can perform arithmetic on individual rows or columns

array([1, 3, 5])

In [54]:
print(np.average(A[:,0])) # average value of the first column of A

0.6666666666666666


Combining matrices or parts of matrices

In [55]:
BlockMatrix = np.block([
    [A,I],
    [B,C]
]) # Array defined in blocks
print(BlockMatrix)

[[2. 0. 1. 1. 0. 0.]
 [0. 1. 2. 0. 1. 0.]
 [0. 0. 3. 0. 0. 1.]
 [0. 0. 0. 1. 1. 1.]
 [0. 0. 0. 1. 1. 1.]]


In [56]:
Concat_Matrix = np.concatenate((A,B),axis=0) # Axis 0 is columns Axis 1 in rows. See what happens when you change 0 to 1.  What is the issue?
print(Concat_Matrix)

[[2. 0. 1.]
 [0. 1. 2.]
 [0. 0. 3.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [57]:
# The shape command gives the dimensions of the matrix.
# If you tried switching axis = 0 to axis = 1, how does this output explain the error you got?
print("This is the shape of matrix A:",np.shape(A))
print("This is the shape of matrix B:",np.shape(B))

This is the shape of matrix A: (3, 3)
This is the shape of matrix B: (2, 3)


In [58]:
np.array([A[1],B[1],C[1]]) # Array built from rows in A, B, and C

array([[0., 1., 2.],
       [0., 0., 0.],
       [1., 1., 1.]])

In [59]:
np.column_stack((A[:,1],I[:,2],A[:,0],A[:,2])) # Array built by combining columns from A and I

array([[0., 0., 2., 1.],
       [1., 0., 0., 2.],
       [0., 1., 0., 3.]])

### Basic Marix Operations

#### Operations on A

In [60]:
np.transpose(A) # Transpose

array([[2, 0, 0],
       [0, 1, 0],
       [1, 2, 3]])

In [61]:
LA.det(A) # Determinant

np.float64(6.0)

In [84]:
np.trace(A) # Trace

np.int64(6)

In [87]:
LA.norm(A) # Euclidean Norm

np.float64(4.358898943540674)

In [62]:
A.max() # Maximum Value

np.int64(3)

In [63]:
A.min() # Minumum Value

np.int64(0)

In [64]:
A.sum() # Sum of all Values

np.int64(9)

In [65]:
A[0].sum() # Sum of values in the first row

np.int64(3)

In [66]:
A[:,0].sum() # sum of values in the first column

np.int64(2)

#### Matrix A and other objects

In [112]:
A_inv = LA.inv(A) # The inverse of A
print(A_inv)

[[ 0.5         0.         -0.16666667]
 [ 0.          1.         -0.66666667]
 [ 0.          0.          0.33333333]]


In [113]:
np.matmul(A,A_inv) == I # Verifying the inverse of A

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [121]:
v=np.array([1,-7,3]) # New Vector
print(v)

[ 1 -7  3]


In [123]:
A+v # Adds v to all the rows of A, this is an example of what is called broadcasting

array([[ 3, -7,  4],
       [ 1, -6,  5],
       [ 1, -7,  6]])

In [75]:
np.matmul(A,v) # A times the column vector v

array([ 5, -1,  9])

In [124]:
np.matmul(v,A) # Vector v as a row vector times A

array([ 2, -7, -4])

In [78]:
np.inner(A[0],v) # First row of A times v as a column, inner product

np.int64(5)

In [125]:
np.outer(A[0],v) # First row of A as a column vector times v as a row vector, outer product

array([[  2, -14,   6],
       [  0,   0,   0],
       [  1,  -7,   3]])

In [105]:
sol_vec = LA.solve(A,v) # calculate the solution to Ax=v
print(sol_vec)

[ 0. -9.  1.]


In [126]:
np.matmul(A,sol_vec) == v # checking that we get v as expected

array([ True,  True,  True])

In [110]:
np.matmul(A_inv,v) == sol_vec # We should get the solution above as the output, this is a cautionary note on round off error

array([False,  True,  True])

In [111]:
print(np.matmul(A_inv,v)) # Note that the first term is "practically" 0

[ 2.77555756e-17 -9.00000000e+00  1.00000000e+00]


In [130]:
A_temp  = LA.det(A)*A_inv # This gives us an integer matrix to work with, why?
print(A_temp)
1/LA.det(A)*np.matmul(A_temp,v) == sol_vec

[[ 3.  0. -1.]
 [ 0.  6. -4.]
 [ 0.  0.  2.]]


array([ True,  True,  True])