In [12]:
import numpy as np
from numpy import linalg as LA
import pandas as pd

## Creating Arrays

### 1d Arrays (Vectors)

The following commands are usefull in creating one dimensional vectors.  As we will see later these are distinct from matrices with one row or one column.

In [2]:
np.array([1,7,9,0]) # Creates a 1X4 array of specific values

array([1, 7, 9, 0])

In [3]:
np.arange(1,5); # 1d array with consecutive terms

In [4]:
np.arange(7,45,10) # From 7 upto, but not exceeding, 45 by 10s

array([ 7, 17, 27, 37])

In [9]:
np.linspace(7, 45, 11) # From 7 to 45 with 11 evenly spaced entries

array([ 7. , 10.8, 14.6, 18.4, 22.2, 26. , 29.8, 33.6, 37.4, 41.2, 45. ])

### 2d Arrays (Matrices)

#### Some Ways to Enter Matrices

First we can create matrices manually:

In [ ]:
I = np.eye(3) # 3x3 identity matrix
A = np.array([
    [2,0,1],
    [0,1,2],
    [0,0,3]
]) # Manually entered array
B = np.zeros((2,3)); # 2x3 zero matrix
C = np.ones((2,3)); # 2x3 matrix of ones
D = np.random.randint(1,20,size=(2,2));

Note that in the commands above a semi-colon after a command suppresses the output.  This is helpful when you are entering initial values/variables but don't need to see the ourtput.

But we can also get matrices by importing data like so:

In [13]:
# Here we import the data and assign each column of values to a variable:
# Notice that as columsn are assigned they are made Numpy arrays
df = pd.read_csv('../data/alcohol_calories.csv')
t = np.array(df['Alcohol'])
oz = np.array(df['oz'])
cal = np.array(df['calories'])
# This calculation creates a Numpy array of calories per oz
cal_per_ounce = cal/oz

In [49]:
print(type(df)) # This shows that df, the data frame, we imported is not an array and so not compatable with the other objects
df_array = np.array(df)
print(type(df_array)) # this is now a numpy array

<class 'pandas.core.frame.DataFrame'>
<class 'numpy.ndarray'>


#### Working with rows and columns

In [7]:
print(A[0]) # this is a row of A, row numbers start at 0

[2 0 1]


In [8]:
print(I[:,1]) # this is a column of I, numbering again starts at 0

[0. 1. 0.]


In [40]:
2*A[1]+1 # we can perform arithmetic on individual rows or columns

array([1, 3, 5])

In [10]:
print(np.average(A[:,0])) # average value of the first column of A

0.6666666666666666


#### Combining matrices or parts of matrices

In [11]:
BlockMatrix = np.block([
    [A,I],
    [B,C]
]) # Array defined in blocks
print(BlockMatrix)

[[2. 0. 1. 1. 0. 0.]
 [0. 1. 2. 0. 1. 0.]
 [0. 0. 3. 0. 0. 1.]
 [0. 0. 0. 1. 1. 1.]
 [0. 0. 0. 1. 1. 1.]]


In [42]:
Concat_Matrix = np.concatenate((A,B),axis=0) # Axis 0 is columns Axis 1 in rows. See what happens when you change 0 to 1.  What is the issue?
print(Concat_Matrix)

[[2. 0. 1.]
 [0. 1. 2.]
 [0. 0. 3.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [ ]:
# The shape command gives the dimensions of the matrix.
# If you tried switching axis = 0 to axis = 1, how does this output explain the error you got?
print("This is the shape of matrix A is %s, while matrix B has shape %s"%(str(np.shape(A)),str(np.shape(B))))

This is the shape of matrix A is (3, 3), while matrix B has shape (2, 3)
This is the shape of matrix B: (2, 3)


In [14]:
np.array([A[1],B[1],C[1]]) # Array built from rows in A, B, and C

array([[0., 1., 2.],
       [0., 0., 0.],
       [1., 1., 1.]])

In [46]:
df_plus = np.column_stack((df_array[:,1:3],cal_per_ounce)); # Here we create an array with just the numerical data from our data frame with the cal/oz added
print(np.shape(df_plus)) # this shows the size of the new array of data

(52, 3)


In [50]:
v = np.array([1,1,1]) # This is just a vector
w = np.array([[1,1,1]]) # This is a matrix
print("This is the shape of vector v is %s, while matrix w has shape %s, thus np.shape(v)==np.shape(w) is False."%(str(np.shape(v)),str(np.shape(w))))

This is the shape of vector v is (3,), while matrix w has shape (1, 3), thus np.shape(v)==np.shape(w) is False.


## Basic Operations

### Vector Operations

In [60]:
min_cal = int(np.min(cal_per_ounce))  # This finds the minimum value in a vector
min_place = int(np.argmin(cal_per_ounce)) # This finds its location
df_array[min_place] # here we see that drink with the fewest calories per ounce is the light beer

array(['Beer (light)', 12.0, 103], dtype=object)

In [67]:
avg_cpo = np.average(cal_per_ounce) # This is finding the average calories per ounce.
print("Here we see that the average calories per ounce in this data set is %0.2f."%avg_cpo)

Here we see that the average calories per ounce in this data set is 43.88.


In [70]:
n = np.shape(cal_per_ounce)[0]
avg_cpo = np.sum(cal_per_ounce)/n
print("Here we recalculated the average calories per ounce, still %0.2f, by summing the entries and dividing by the number of rows"%avg_cpo)

Here we recalculated the average calories per ounce, still 43.88, by summing the entries and dividing by the number of rows


In [76]:
# This creates three "large" random vectors
v = np.random.rand(42,)
w = np.random.rand(42,)
u = np.random.rand(42,)
print("v=%s\n\n w=%s\n\n u=%s"%(v,w,u))

v=[0.34162129 0.34596886 0.25097628 0.33509977 0.50720447 0.12647195
 0.75892854 0.37208604 0.88157789 0.91798707 0.64703095 0.93868355
 0.02157209 0.5500054  0.17187958 0.34785719 0.96944697 0.03256866
 0.24170396 0.62513683 0.61397071 0.31430387 0.60041287 0.78958649
 0.06259206 0.83409154 0.82176021 0.97748511 0.97450153 0.26242974
 0.81924443 0.81577943 0.33915693 0.31074615 0.03608822 0.65060616
 0.55215072 0.71389137 0.41934541 0.93973877 0.14345007 0.82434143]

 w=[0.21934972 0.74827184 0.84109019 0.0648512  0.93642511 0.33771302
 0.0882782  0.62317131 0.9718445  0.75375776 0.06865732 0.86937497
 0.03518887 0.45274108 0.7318425  0.90223378 0.28022135 0.58422293
 0.84594256 0.0848792  0.42651982 0.95499628 0.41831885 0.61614893
 0.03788403 0.4866475  0.23802943 0.00150414 0.31936488 0.52809638
 0.50673924 0.11761919 0.98375381 0.49611482 0.78593298 0.90364893
 0.62219723 0.90043504 0.96197412 0.33449128 0.28469473 0.63605425]

 u=[0.03348078 0.8146889  0.09066942 0.3857973  0.285

In [80]:
print(np.dot(v,w)) # This calculates the dot product of v and w
print(np.inner(v,w)) # This calculates the inner product of v and w
# These are the same for one dimensional arrays, for more details on when ther differ you can look at
# https://numpy.org/doc/2.3/reference/generated/numpy.inner.html

11.269297215899401
11.269297215899401


We can use the dot product to find vector projections and create orthogonal vectors:

In [ ]:
proj_w = np.dot(v,w)/np.dot(v,v) * v
w_hat = w - proj_w
print("To the nearest 1000th, the new vector is orthogonal to v, dot product of %0.3f"%abs(np.dot(v,w_hat)))

To the nearest 1000th, the new vector is orthogonal to v, dot product of 0.000


We can also use the norm command from the linear algebra library instead of using the dot product of a vector with its self

In [92]:
proj_u1 = np.dot(v,u)/np.linalg.norm(v)**2 *v
proj_u2 = np.dot(w_hat,u)/np.linalg.norm(w_hat)**2 *w_hat
p = proj_u1 + proj_u2
u_hat = u-p
print("To the nearest 1000th, the new vector is orthogonal to v, dot product of %0.3f"%abs(np.dot(v,u_hat)))
print("To the nearest 1000th, the new vector is orthogonal to w_hat, dot product of %0.3f"%abs(np.dot(w_hat,u_hat)))

To the nearest 1000th, the new vector is orthogonal to v, dot product of 0.000
To the nearest 1000th, the new vector is orthogonal to w_hat, dot product of 0.000


This is creating a matrix with columns which are orthogonal and have length one.  How are the columns adjusted in length?

In [ ]:
Ortho_Normal_Example = np.column_stack((v/np.linalg.norm(v),w_hat/np.linalg.norm(w_hat),u_hat/np.linalg.norm(u_hat))) 

### Uninary Operations on $A$

In [99]:
np.transpose(A) # Transpose

array([[2, 0, 0],
       [0, 1, 0],
       [1, 2, 3]])

In [100]:
LA.det(A) # Determinant

np.float64(6.0)

In [101]:
np.trace(A) # Trace

np.int64(6)

In [102]:
LA.norm(A) # Euclidean Norm

np.float64(4.358898943540674)

In [103]:
A.max() # Maximum Value

np.int64(3)

In [104]:
A.min() # Minumum Value

np.int64(0)

In [105]:
A.sum() # Sum of all Values

np.int64(9)

In [23]:
A[0].sum() # Sum of values in the first row

np.int64(3)

In [106]:
A[:,0].sum() # sum of values in the first column

np.int64(2)

In [107]:
A_inv = LA.inv(A) # The inverse of A
print(A_inv)

[[ 0.5         0.         -0.16666667]
 [ 0.          1.         -0.66666667]
 [ 0.          0.          0.33333333]]


### Binary Operations of Matrix A and other objects

In [108]:
np.matmul(A,A_inv) == I # Verifying the inverse of A

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [123]:
Ortho_Transpose = np.transpose(Ortho_Normal_Example)
np.round(Ortho_Transpose @ Ortho_Normal_Example, 15) == I

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [125]:
Ortho_Transpose+v # Adds v to all the rows of Ortho_Transpose, this is an example of what is called broadcasting

array([[0.42834378, 0.433795  , 0.31468802, 0.42016674, 0.63596119,
        0.15857756, 0.95158684, 0.46654218, 1.10537142, 1.15102327,
        0.81128341, 1.17697368, 0.02704829, 0.68962738, 0.21551219,
        0.4361627 , 1.21554656, 0.04083639, 0.30306188, 0.78383134,
        0.76983065, 0.39409168, 0.75283107, 0.99002749, 0.07848141,
        1.04583039, 1.03036868, 1.22562523, 1.22188425, 0.32904901,
        1.02721426, 1.02286965, 0.42525384, 0.38963081, 0.04524942,
        0.81576621, 0.69231731, 0.89511672, 0.52579861, 1.17829677,
        0.17986568, 1.03360515],
       [0.33109626, 0.52796153, 0.49221631, 0.26973668, 0.71521701,
        0.21649998, 0.58943945, 0.50132597, 1.00300677, 0.94987789,
        0.50011306, 1.00740599, 0.02872066, 0.56952725, 0.39415005,
        0.58572349, 0.81426023, 0.23783116, 0.48718646, 0.48998092,
        0.60688159, 0.58041253, 0.59392612, 0.80523369, 0.05981952,
        0.79048484, 0.69039693, 0.71810384, 0.83230376, 0.38601608,
        0.78694

In [ ]:
np.matmul(Ortho_Transpose,v) # Ortho_Transpose times the column vector v

array([ 3.93924659e+00, -1.61329283e-16, -4.16333634e-16])

In [128]:
np.matmul(v,Ortho_Normal_Example) # Vector v as a row vector times Ortho_Normal_Example

array([ 3.93924659e+00, -1.61329283e-16, -4.16333634e-16])

In [129]:
np.inner(Ortho_Transpose[1],v) # Second row of Ortho_Transpose times v as a column, inner product

np.float64(-1.3183898417423734e-16)

In [130]:
np.outer(Ortho_Transpose[1],v) # Second row of Ortho_Transpose as a column vector times v as a row vector, outer product

array([[-0.00359557, -0.00364133, -0.00264153, ..., -0.00989078,
        -0.00150982, -0.00867622],
       [ 0.06217257,  0.0629638 ,  0.04567584, ...,  0.17102557,
         0.02610686,  0.1500241 ],
       [ 0.08241273,  0.08346154,  0.06054553, ...,  0.22670261,
         0.0346059 ,  0.19886415],
       ...,
       [-0.04352764, -0.04408159, -0.03197812, ..., -0.11973672,
        -0.01827768, -0.10503338],
       [ 0.02258106,  0.02286843,  0.01658945, ...,  0.06211643,
         0.009482  ,  0.0544887 ],
       [ 0.00467811,  0.00473765,  0.00343683, ...,  0.01286865,
         0.00196439,  0.01128842]], shape=(42, 42))

### Solving Expressions $Ax=v$

In [138]:
v = np.random.randint(-5,5,size=(3,))
sol_vec = LA.solve(A,v) # calculate the solution to Ax=v
print(sol_vec)

[-1.5 -7.   1. ]


In [139]:
np.round(np.matmul(A,sol_vec),0) == v # checking that we get v as expected

array([ True,  True,  True])

In [140]:
np.matmul(A,sol_vec) == v # if we don't round it off we get errors, this is a cautionary note on round off error

array([ True,  True,  True])

In [141]:
np.matmul(A_inv,v) # We can also find the solution using inverse matrices, this is sometimes more prone to round off error

array([-1.5, -7. ,  1. ])

In [142]:
A_temp  = LA.det(A)*A_inv # This gives us an integer matrix to work with, why?
print(A_temp)
1/LA.det(A)*np.matmul(A_temp,v) == sol_vec

[[ 3.  0. -1.]
 [ 0.  6. -4.]
 [ 0.  0.  2.]]


array([ True,  True,  True])