In [2]:
import numpy as np
from numpy import linalg as LA

### Useful Commands for the First Project About Powers

First I will input a matrix

In [3]:
A = np.array([[1,2,0],[0,3,1],[0,2,0]])

In [5]:
print(A)

[[1 2 0]
 [0 3 1]
 [0 2 0]]


Raise the matrix to powers

In [ ]:
# Clumsy Multiplication
A@A@A@A@A

array([[  1, 386, 108],
       [  0, 495, 139],
       [  0, 278,  78]])

In [18]:
B = np.matmul(A,B)
print(B)

[[  1 386 108]
 [  0 495 139]
 [  0 278  78]]


In [19]:
np.linalg.matrix_power(A,5)

array([[  1, 386, 108],
       [  0, 495, 139],
       [  0, 278,  78]])

In [23]:
B=LA.matrix_power(A,5)

Pull off individual columns of the matrix

In [24]:
print(B)

[[  1 386 108]
 [  0 495 139]
 [  0 278  78]]


In [36]:
B[:,0]

array([1, 0, 0])

In [37]:
B[:,1]

array([386, 495, 278])

In [38]:
B[:,2]

array([108, 139,  78])

### Useful Commands for the Second Project

In [42]:
np.poly(A)

array([ 1., -4.,  1.,  2.])

In [43]:
print(A)

[[1 2 0]
 [0 3 1]
 [0 2 0]]


In [47]:
np.linalg.det(A)

np.float64(-2.0)

In [48]:
LA.qr(A)

QRResult(Q=array([[ 1.        ,  0.        ,  0.        ],
       [-0.        , -0.83205029, -0.5547002 ],
       [-0.        , -0.5547002 ,  0.83205029]]), R=array([[ 1.        ,  2.        ,  0.        ],
       [ 0.        , -3.60555128, -0.83205029],
       [ 0.        ,  0.        , -0.5547002 ]]))

In [49]:
# This works better if you give them a name
Q,R = LA.qr(A)

In [50]:
print(Q)

[[ 1.          0.          0.        ]
 [-0.         -0.83205029 -0.5547002 ]
 [-0.         -0.5547002   0.83205029]]


In [51]:
print(R)

[[ 1.          2.          0.        ]
 [ 0.         -3.60555128 -0.83205029]
 [ 0.          0.         -0.5547002 ]]


In [52]:
np.triu(A)

array([[1, 2, 0],
       [0, 3, 1],
       [0, 0, 0]])

In [53]:
print(A)

[[1 2 0]
 [0 3 1]
 [0 2 0]]


In [61]:
C = np.ones((5,5))

In [62]:
print(C)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [67]:
np.triu(C)

array([[1., 1., 1., 1., 1.],
       [0., 1., 1., 1., 1.],
       [0., 0., 1., 1., 1.],
       [0., 0., 0., 1., 1.],
       [0., 0., 0., 0., 1.]])

In [68]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [69]:
np.zeros((5,7))

array([[0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.]])

In [70]:
np.ones((7,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

### Other Useful Things

In [72]:
# This is a for loop
B=A
for i in range(5):
    print(B)
    B = np.matmul(B,A)

[[1 2 0]
 [0 3 1]
 [0 2 0]]
[[ 1  8  2]
 [ 0 11  3]
 [ 0  6  2]]
[[ 1 30  8]
 [ 0 39 11]
 [ 0 22  6]]
[[  1 108  30]
 [  0 139  39]
 [  0  78  22]]
[[  1 386 108]
 [  0 495 139]
 [  0 278  78]]


In [76]:
# While Loop
B = A
i = 0
while i<5:
    print(B)
    B = np.matmul(B,A)
    i += 1

[[1 2 0]
 [0 3 1]
 [0 2 0]]
[[ 1  8  2]
 [ 0 11  3]
 [ 0  6  2]]
[[ 1 30  8]
 [ 0 39 11]
 [ 0 22  6]]
[[  1 108  30]
 [  0 139  39]
 [  0  78  22]]
[[  1 386 108]
 [  0 495 139]
 [  0 278  78]]


In [75]:
# Finding Transposes
A.T

array([[1, 0, 0],
       [2, 3, 2],
       [0, 1, 0]])

In [82]:
# Eigenvalues and vectors
vals,vecs = LA.eig(A)
print(vals)
print(vecs)

[ 1.          3.56155281 -0.56155281]
[[ 1.          0.56275139  0.3271692 ]
 [ 0.          0.7207587  -0.25544599]
 [ 0.          0.40474408  0.9097844 ]]
