In [1]:
import numpy as np
from numpy import linalg as LA

## Creating Arrays

### 1d Arrays (Vectors)

In [2]:
np.array([1,7,9,0]) # Creates a 1X4 array of specific values

array([1, 7, 9, 0])

In [ ]:
v = arange(1,5); # 1d array with consecutive terms

In [4]:
np.arange(7,45,10) # From 7 upto, but not exceeding, 45 by 10s

array([ 7, 17, 27, 37])

In [5]:
np.linspace(7, 37, 11) # From 7 to 45 with 11 evenly spaced entries

array([ 7., 10., 13., 16., 19., 22., 25., 28., 31., 34., 37.])

Note that in the commands above a semi-colon after a command suppresses the output.  This is helpful when you are entering initial values/variables but don't need to see the ourtput.

### 2d Arrays (Matrices)

In [38]:
I = np.eye(3) # 3x3 identity matrix
A = np.array([
    [2,0,1],
    [0,1,2],
    [0,0,3]
]) # Manually entered array
B = np.zeros((2,3)); # 2x3 zero matrix
C = np.ones((2,3)); # 2x3 matrix of ones

In [4]:
D = np.array([[1,2],[3,4],[5,6]])

Working with rows and columns

In [7]:
print(A[0]) # this is a row of A, row numbers start at 0

[2 0 1]


In [8]:
print(I[:,1]) # this is a column of I, numbering again starts at 0

[0. 1. 0.]


In [40]:
2*A[1]+1 # we can perform arithmetic on individual rows or columns

array([1, 3, 5])

In [10]:
print(np.average(A[:,0])) # average value of the first column of A

0.6666666666666666


Combining matrices or parts of matrices

In [11]:
BlockMatrix = np.block([
    [A,I],
    [B,C]
]) # Array defined in blocks
print(BlockMatrix)

[[2. 0. 1. 1. 0. 0.]
 [0. 1. 2. 0. 1. 0.]
 [0. 0. 3. 0. 0. 1.]
 [0. 0. 0. 1. 1. 1.]
 [0. 0. 0. 1. 1. 1.]]


In [42]:
Concat_Matrix = np.concatenate((A,B),axis=0) # Axis 0 is columns Axis 1 in rows. See what happens when you change 0 to 1.  What is the issue?
print(Concat_Matrix)

[[2. 0. 1.]
 [0. 1. 2.]
 [0. 0. 3.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [ ]:
# The shape command gives the dimensions of the matrix.
# If you tried switching axis = 0 to axis = 1, how does this output explain the error you got?
print("This is the shape of matrix A is %s, while matrix B has shape %s"%(str(np.shape(A)),str(np.shape(B))))

This is the shape of matrix A is (3, 3), while matrix B has shape (2, 3)
This is the shape of matrix B: (2, 3)


In [14]:
np.array([A[1],B[1],C[1]]) # Array built from rows in A, B, and C

array([[0., 1., 2.],
       [0., 0., 0.],
       [1., 1., 1.]])

In [15]:
np.column_stack((A[:,1],I[:,2],A[:,0],A[:,2])) # Array built by combining columns from A and I

array([[0., 0., 2., 1.],
       [1., 0., 0., 2.],
       [0., 1., 0., 3.]])

In [ ]:
v = np.array([1,1,1])
w = np.array([[1,1,1]])
print("This is the shape of vector v is %s, while matrix w has shape %s, thus np.shape(v)==np.shape(w) is False."%(str(np.shape(v)),str(np.shape(w))))

This is the shape of vector v is (3,), while matrix w has shape (1, 3), thus np.shape(v)==np.shape(w) is False.


## Basic Marix Operations

### Uninary Operations on $A$

In [16]:
np.transpose(A) # Transpose

array([[2, 0, 0],
       [0, 1, 0],
       [1, 2, 3]])

In [17]:
LA.det(A) # Determinant

np.float64(6.0)

In [18]:
np.trace(A) # Trace

np.int64(6)

In [19]:
LA.norm(A) # Euclidean Norm

np.float64(4.358898943540674)

In [20]:
A.max() # Maximum Value

np.int64(3)

In [21]:
A.min() # Minumum Value

np.int64(0)

In [22]:
A.sum() # Sum of all Values

np.int64(9)

In [23]:
A[0].sum() # Sum of values in the first row

np.int64(3)

In [24]:
A[:,0].sum() # sum of values in the first column

np.int64(2)

In [25]:
A_inv = LA.inv(A) # The inverse of A
print(A_inv)

[[ 0.5         0.         -0.16666667]
 [ 0.          1.         -0.66666667]
 [ 0.          0.          0.33333333]]


### Binary Operations of Matrix A and other objects

In [26]:
np.matmul(A,A_inv) == I # Verifying the inverse of A

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [57]:
v=np.array([1,-7,3]) # New Vector
w=np.array([[1,-7,3]]) # New Matrix
print(v,"\n",w)

[ 1 -7  3] 
 [[ 1 -7  3]]


In [59]:
A+v # Adds v to all the rows of A, this is an example of what is called broadcasting

array([[ 3, -7,  4],
       [ 1, -6,  5],
       [ 1, -7,  6]])

In [29]:
np.matmul(A,v) # A times the column vector v

array([ 5, -1,  9])

In [30]:
np.matmul(v,A) # Vector v as a row vector times A

array([ 2, -7, -4])

In [31]:
np.inner(A[0],v) # First row of A times v as a column, inner product

np.int64(5)

In [32]:
np.outer(A[0],v) # First row of A as a column vector times v as a row vector, outer product

array([[  2, -14,   6],
       [  0,   0,   0],
       [  1,  -7,   3]])

### Solving Expressions $Ax=v$

In [33]:
sol_vec = LA.solve(A,v) # calculate the solution to Ax=v
print(sol_vec)

[ 0. -9.  1.]


In [34]:
np.matmul(A,sol_vec) == v # checking that we get v as expected

array([ True,  True,  True])

In [35]:
np.matmul(A_inv,v) == sol_vec # We should get the solution above as the output, this is a cautionary note on round off error

array([False,  True,  True])

In [36]:
print(np.matmul(A_inv,v)) # Note that the first term is "practically" 0

[ 2.77555756e-17 -9.00000000e+00  1.00000000e+00]


In [37]:
A_temp  = LA.det(A)*A_inv # This gives us an integer matrix to work with, why?
print(A_temp)
1/LA.det(A)*np.matmul(A_temp,v) == sol_vec

[[ 3.  0. -1.]
 [ 0.  6. -4.]
 [ 0.  0.  2.]]


array([ True,  True,  True])

In [67]:
np.inner(v,w)

array([59])