In [1]:
import numpy as np
from numpy import linalg as la

In [2]:
A = np.array([[2,-1],[1,-2]])

In [3]:
print(A)

[[ 2 -1]
 [ 1 -2]]


In [4]:
B = np.array([[2,1,3],[0,2,-5]])
B

array([[ 2,  1,  3],
       [ 0,  2, -5]])

In [5]:
A@B

array([[ 4,  0, 11],
       [ 2, -3, 13]])

In [6]:
B@A

ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 2 is different from 3)

In [7]:
A.shape

(2, 2)

In [8]:
B.shape

(2, 3)

In [9]:
A.shape[1] == B.shape[0] 

True

In [10]:
B.shape[1] == A.shape[0]

False

In [13]:
def my_mult(X,Y):
    if X.shape[1] == Y.shape[0]:
        product = np.matmul(X,Y)
    else:
        print("Dimension mismatch")
        product = 0
    return product

In [14]:
my_mult(B,A)

Dimension mismatch


0