In [1]:
import numpy as np

# Step 1: I Define the matrix A
A = np.array([
    [6,  -4,  -8],
    [-3, 10,  11],
    [2,  -4,  -4]
], dtype=float)

# Step 2. I Scale A by 6 to get A/6

A6 = A / 6.0

print("Matrix A:")
print(A)
print("\nMatrix A/6:")
print(A6)

# Step 3. I will Explore high powers of A/6
exponents = [1, 2, 5, 10, 20, 50, 100]

print("\nHigh powers of A/6:\n")
for k in exponents:
    Bk = np.linalg.matrix_power(A6, k)
    print(f"(A/6)^{k} ≈")
    print(np.round(Bk, 6))   # I rounded for better display
    print()

# Step 4: I will Check how much high powers change
print("Differences between successive high powers:\n")
prev = None
for k in exponents:
    Bk = np.linalg.matrix_power(A6, k)
    if prev is not None:
        diff = np.linalg.norm(Bk - prev)
        print(f"|| (A/6)^{k} - (A/6)^{prev_k} ||_F = {diff:.6e}")
    prev = Bk
    prev_k = k


Matrix A:
[[ 6. -4. -8.]
 [-3. 10. 11.]
 [ 2. -4. -4.]]

Matrix A/6:
[[ 1.         -0.66666667 -1.33333333]
 [-0.5         1.66666667  1.83333333]
 [ 0.33333333 -0.66666667 -0.66666667]]

High powers of A/6:

(A/6)^1 ≈
[[ 1.       -0.666667 -1.333333]
 [-0.5       1.666667  1.833333]
 [ 0.333333 -0.666667 -0.666667]]

(A/6)^2 ≈
[[ 0.888889 -0.888889 -1.666667]
 [-0.722222  1.888889  2.5     ]
 [ 0.444444 -0.888889 -1.222222]]

(A/6)^5 ≈
[[ 0.62963  -0.995885 -1.621399]
 [-0.932099  1.995885  2.923868]
 [ 0.497942 -0.995885 -1.489712]]

(A/6)^10 ≈
[[ 0.517333 -0.999983 -1.517299]
 [-0.991321  1.999983  2.991287]
 [ 0.499992 -0.999983 -1.499958]]

(A/6)^20 ≈
[[ 0.500301 -1.       -1.500301]
 [-0.99985   2.        2.99985 ]
 [ 0.5      -1.       -1.5     ]]

(A/6)^50 ≈
[[ 0.5 -1.  -1.5]
 [-1.   2.   3. ]
 [ 0.5 -1.  -1.5]]

(A/6)^100 ≈
[[ 0.5 -1.  -1.5]
 [-1.   2.   3. ]
 [ 0.5 -1.  -1.5]]

Differences between successive high powers:

|| (A/6)^2 - (A/6)^1 ||_F = 1.042315e+00
|| (A/6)^5 - 