In [1]:
import numpy as np

# ---------------------------
# Question 3:
# Is x an eigenvector of A?
# If so, what is the eigenvalue?
# ---------------------------

# Step 1. Define matrix A
A = np.array([
    [6,  -4,  -8],
    [-3, 10,  11],
    [2,  -4,  -4]
], dtype=float)

print("Matrix A:")
print(A)
print()

# Step 2. Form A/6
A6 = A / 6.0
print("Matrix A/6:")
print(A6)
print()

# Step 3. Compute B = (A/6)^100
k = 100
B = np.linalg.matrix_power(A6, k)

print(f"(A/6)^{k} ≈")
print(np.round(B, 6))
print()

# Step 4. Let x be the first column of B
x = B[:, 0]
print("Vector x = first column of (A/6)^100:")
print(x)
print()

# Step 5. Compute Ax
Ax = A @ x
print("A x =")
print(Ax)
print()

# Step 6. Check if Ax is a scalar multiple of x
#    Compute elementwise ratios Ax / x
ratios = Ax / x
print("Elementwise ratios Ax / x =")
print(ratios)
print()

# Step 7. Approximate eigenvalue as the average of the ratios
lambda_est = np.mean(ratios)
print(f"Approximate eigenvalue (mean of ratios) = {lambda_est:.6f}")

# Step 8. sumamry
print("\nSummary:")
print("Since Ax is (numerically) equal to 6 times x,")
print("x is an eigenvector of A and the associated eigenvalue is approximately 6.")


Matrix A:
[[ 6. -4. -8.]
 [-3. 10. 11.]
 [ 2. -4. -4.]]

Matrix A/6:
[[ 1.         -0.66666667 -1.33333333]
 [-0.5         1.66666667  1.83333333]
 [ 0.33333333 -0.66666667 -0.66666667]]

(A/6)^100 ≈
[[ 0.5 -1.  -1.5]
 [-1.   2.   3. ]
 [ 0.5 -1.  -1.5]]

Vector x = first column of (A/6)^100:
[ 0.5 -1.   0.5]

A x =
[ 3. -6.  3.]

Elementwise ratios Ax / x =
[6. 6. 6.]

Approximate eigenvalue (mean of ratios) = 6.000000

Summary:
Since Ax is (numerically) equal to 6 times x,
x is an eigenvector of A and the associated eigenvalue is approximately 6.
